### ISSUE TITLE
Compiling error on Ubuntu 16.04

### ISSUE THREAD

**Issue by yinzheng-zhong** [deeponion/deeponion-legacy#106]
Hi. I got this error when compiling.

qt/qt_DeepOnion_qt-bitcoin.o: In function `main':
/home/**/deeponion/src/qt/bitcoin.cpp:129: undefined reference to `qInitResources_bitcoin()'
collect2: error: ld returned 1 exit status
Makefile:2244: recipe for target 'qt/DeepOnion-qt' failed
make[1]: *** [qt/DeepOnion-qt] Error 1
make[1]: Leaving directory '/home/**/deeponion/src'
Makefile:542: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I tried this
https://github.com/deeponion/deeponion/issues/75
but still got the same error.

I think this problem arose after a commitment after 1.6.3 (Not sure the exact commitment, first 1.6.3 release compiles fine).
1.7 is important so could you please help me out? Thank you!

**Comment by nezero** [comment]
It's a known problem with the QT build tools. Please use this command to work around the issue.

`touch src/qt/bitcoin.qrc`

the run make again.

**Comment by yinzheng-zhong** [comment]
That works. The key is running make again after touch. Thank you.

**Comment by aitorp6** [comment]
@zxhaxdr I think that I know where the problem is. 

Do the following, after cloning the repository, do `qmake` before doing `./autogen.sh`

Tell me if it works.

**Comment by aitorp6** [comment]
@nezero @zxhaxdr I have done the following, after cloning the repo, I have done `qmake` before doing  `\autogen.sh`

This has worker for me.
