### ISSUE TITLE
Add support for watch-only addresses

### ISSUE THREAD

**Issue by obszoenling** [deeponion/deeponion-legacy#108]
I would like to watch address balances via RPC, that don't belong to the wallet, in order to not depend on 3-party-explorers. `getreceivedbyaddress` doesn't work with addresses out of your own wallet. That's why later `importaddress` has been added to Bitcoin, that don't need private keys and are ignored for balance calculating.
https://bitcoin.org/en/developer-reference#importaddress
Pull Request: https://github.com/bitcoin/bitcoin/pull/4045

I would like to have this feature also for Deeponion to use it for an independent light explorer/monitor application.

**Comment by deeponion** [comment]
Thanks for the suggestion, we are looking into it

**Comment by deeponion** [comment]
This will be done in the rebased code.
