### ISSUE TITLE
Error when ./DeepOniond getmininginfo

### ISSUE THREAD

**Issue by errnouser** [deeponion/deeponion-legacy#11]
============================================================ T= 1504359579
Tor 0.2.5.1-alpha-dev died: Caught signal 11
./DeepOniond[0x42e052]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f12ab800890]
./DeepOniond[0x5e03f4]
./DeepOniond[0x5e0558]
./DeepOniond[0x65b914]
./DeepOniond[0x620233]
./DeepOniond[0x6222c5]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0(+0xdaea)[0x7f12acee2aea]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064)[0x7f12ab7f9064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f12aab0062d]
Aborted

**Comment by deeponion** [comment]
which machine you tried this? I tried on linux, no problem:

root@vmi:~/# ./DeepOniond getmininginfo
{
    "blocks" : 297057,
    "currentblocksize" : 1000,
    "currentblocktx" : 0,
    "difficulty" : {
        "proof-of-work" : 80892.41270200,
        "proof-of-stake" : 1.11014179,
        "search-interval" : 1
    },
    "blockvalue" : 800000000,
    "netmhashps" : 1867904.66155713,
    "netstakeweight" : 78725724.66383228,
    "errors" : "",
    "pooledtx" : 0,
    "stakeweight" : {
        "minimum" : 0,
        "maximum" : 0,
        "combined" : 0
    },
    "testnet" : false
}
