### ISSUE TITLE
Error compiling deeponion-qt in ubuntu 17.04

### ISSUE THREAD

**Issue by luxferrari** [deeponion/deeponion-legacy#14]
Hi! When trying to compile deeponion-qt on Ubuntu 17.04 I encountered two issues.

First, before compiling leveldb (as suggested [here](https://deeponion.org/community/threads/article-build-the-qt-wallet-on-ubuntu.3726/)) I had to chmod 755 the script `build_detect_platform`, it was not executable (I pulled everything from git).

Then when compiling deeponion-qt I got: 

`/home/***/deeponion/src/net.cpp:1008: warning: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                    ^~~~~~`
`/home/***/deeponion/src/net.cpp:1008: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                          ^`

(Actually, "make" just stopped saying something about build/net.o, above error is pasted from Qt Creator)
A similar error [was reported to the guys from dogecoin's wallet](https://github.com/dogecoin/dogecoin/issues/1292), so I'm hoping you can fix it as well.

Regards

**Comment by deeponion** [comment]
now with autotools for build it should be smooth.
