### ISSUE TITLE
qmake translation tag typo's

### ISSUE THREAD

**Issue by nezero** [deeponion/deeponion-legacy#15]
`lrelease error: Unexpected tag <translatio> at /home/neo/Downloads/deeponion/src/qt/locale/bitcoin_sc.ts:824:20`

`lrelease error: Unexpected tag <translatio> at /home/neo/Downloads/deeponion/src/qt/locale/bitcoin_sc.ts:1013:20`

`lrelease error: Parse error at /home/neo/Downloads/deeponion/src/qt/locale/bitcoin_sc.ts:2593:14: Opening and ending tag mismatch.`

`lrelease error: Parse error at /home/neo/Downloads/deeponion/src/qt/locale/bitcoin_sc.ts:2873:55: Expected ';', but got '<'.`

`lrelease error: Parse error at /home/neo/Downloads/deeponion/src/qt/locale/bitcoin_sc.ts:3210:47: Expected ';', but got ' '.`

Fixes to get it to build attached.

[bitcoin_sc.ts.txt](https://github.com/deeponion/deeponion/files/1374774/bitcoin_sc.ts.txt)

**Comment by ccfiel** [comment]
same here. Using ubuntu 16.04. any fix for this?

**Comment by nezero** [comment]
See the file I attached, you'll have to fix it your self until the dev team pull in the change. I think someone has added a pull request.

**Comment by nezero** [comment]
Closed accidentally!

**Comment by ilovelinux** [comment]
I just made a pull request: #18

**Comment by fuss132** [comment]
This should really be addressed. It's such a simple pull request, why is nobody actively developing on this repository?

**Comment by deeponion** [comment]
pull request accepted, case closed. thanks.
