### ISSUE TITLE
Automatic wallet start

### ISSUE THREAD

**Issue by ghost** [deeponion/deeponion-legacy#152]
Right now when I download the wallet and choose a custom location for its files (Windows), every time I run it again it will ask me for the location again (as if it was a first, clean start). This prevents me from setting the wallet to start automatically with the system start.

I would like the wallet to be able to remember its custom file location, so it can start automatically with the system start without my assist.

Thank you

**Comment by deeponion** [comment]
what you can to do is to create a shortcut, then edit it to put the customer conf dir location there. For example, in windows you can edit the shortcut property and add something like this: 
(exe dir)\DeepOnion-qt.exe -dataDir=(config dir)

replace exe_dir and config_dir with your corresponding dir.

then each time click on the shortcut to start.
