### ISSUE TITLE
macOS wallet cross compilation

### ISSUE THREAD

**Issue by godlovedamian** [deeponion/deeponion-legacy#160]
I'm trying to cross compile the DeepOnion wallet with instructions from [the documentation](https://github.com/deeponion/deeponion/blob/master/doc/release-process.txt) (which does seem to be outdated) with no success, as the version I can build on my macbook using instructions from [the documentation](https://github.com/deeponion/deeponion/blob/master/doc/build_macos.md) does not run on any other macbook. I've done my research and it seems Apple does link libs dynamically hence the final dmg build can only run on the same machine it was built on, any help would be appreciated, thanks in advance :)  !

**Comment by nezero** [comment]
Please come to the forums for issues like these, this is not an issue with the source code.

**Comment by godlovedamian** [comment]
Sorry about that, I found out late about the forum. I'm going to close this now
