### ISSUE TITLE
json-rpc 403's despite -rpcallowip

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [deeponion/deeponion-legacy#161]
Hi, I'm running DeepOnion version v1.7.1.1
My DeepOnion.conf contains:
```
[...]
rpcuser=XXX
rpcpassword=XXX
testnet=0
listen=1
rpcallowip=127.0.0.0/8
rpcallowip=192.168.1.0/24
debug=1
[...]
```

Unfortunately, telneting from 192.168.1.0/24 network gives 403 no matter wherher request was sent or not:
```
curl 192.168.1.1:1234 -v
* About to connect() to 192.168.1.1 port 1234 (#0)
*   Trying 192.168.1.1...
* Connected to 192.168.1.1 (192.168.1.1 port 1234 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.1.1:1234
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Date: Fri, 14 Sep 2018 11:17:31 +0000
< Connection: close
< Content-Length: 0
< Content-Type: application/json
< Server: DeepOnion-json-rpc/v1.7.1.1
< 
* Closing connection 0
```

I've tried rpcallowip=192.168.1.*, 1.0/24, and 0.0.0.0/0
Maybe there should be github wiki page about this?

**Comment by Igor-san** [comment]
Try with
server=1

**Comment by nezero** [comment]
Please come to the Forums for support. https://deeponion.org/community/ this appears to be configuration and not a bug in the code.
