### ISSUE TITLE
Update the DeepOnion TOR implementation 

### ISSUE THREAD

**Issue by 2bug** [deeponion/deeponion-legacy#17]
hi dev,
The TOR version as shipped with deeponion( 0.2.5.1-alpha-dev) is forked from upstream in early 2014, somewhere between 0.2.5.1-alpha and 0.2.5.2-alpha. 

Current stable in 0.2.5-branch is 0.2.5.15. 
There are tons of bugs and security issues that were reported and fixed upstream in the meantime and 0.2.5-support ends 1 May 2018.
https://gitweb.torproject.org/tor.git/plain/ReleaseNotes

**Comment by deeponion** [comment]
yes we are working on it. thanks.

**Comment by deeponion** [comment]
tor is upgraded to the latest now.
