### ISSUE TITLE
Starting the software requires a long wait process

### ISSUE THREAD

**Issue by githubvipuser** [deeponion/deeponion-legacy#172]
It takes a lot of time to start the wallet
Mouse click does not respond after the program interface appears
This situation is usually only a few minutes on bitcoin-qt.
And deeponion takes about half an hour.
Sync is complete

**Comment by thohemp** [comment]
Can you tell more about your operation system?

**Comment by githubvipuser** [comment]
> Can you tell more about your operation system?

Restart the computer after the synchronization is completely completed
The problem is solved
