### ISSUE TITLE
leveldb/libleveldb.a Error 1

### ISSUE THREAD

**Issue by suryapratap1** [deeponion/deeponion-legacy#173]
if anyone knows please let me know asap !!

leveldb/libleveldb.a Error 1

**Comment by nezero** [comment]
You are going to have to provide a lot more information.

**Comment by suryapratap1** [comment]
@nezero
 please take a look here is given screenshot.and help me asap please !!


![virtualbox_windows _22_11_2018_10_08_57](https://user-images.githubusercontent.com/31241756/48882181-0344f000-ee3f-11e8-852c-e99523109917.png)

**Comment by nezero** [comment]
Beepmagnet.pro? I think you need to raise your issue here https://github.com/dongilead/beepmagnet-coin-core

**Comment by suryapratap1** [comment]
@nezero Thanks for your fast reply, actually i am a student and new at cryptocurrency development . Beepmagnet is just a cryptocoin which i took to learn for making a window wallet like .exe , if i am going to build some other cryptocoin likewise in bitcoin and also deeponion then also i face same problem . so can you help me please to find out a way to short out this kind of leveldb problem !!!

**Comment by nezero** [comment]
https://github.com/deeponion/deeponion/blob/master/doc/build-windows.md

I've never built on Windows, though you should follow the above guide to do so.

**Comment by suryapratap1** [comment]
@nezero Thanks for your fast reply
