### ISSUE TITLE
Plentey Security Vulnerabilities in OpenSSL 1.0.1l

### ISSUE THREAD

**Issue by DeepBrotherhood** [deeponion/deeponion-legacy#176]
https://www.cvedetails.com/vulnerability-list.php?vendor_id=217&product_id=383&version_id=180646&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&cweid=0&order=1&trc=36&sha=7653fbcb234aa07e1b868fbd70946317d85ca17f

The DeepOnion Wallet use OpenSSL 1.0.1l  from the 15 Jan 2015
it is high time to update the client once.

**Comment by nezero** [comment]
This is something that is in progress.

**Comment by ShinaWong8888** [comment]
Stop sending me this shit you dumb motherfucker
