### ISSUE TITLE
The Mac Code does not work below High Sierra

### ISSUE THREAD

**Issue by lukzluthor** [deeponion/deeponion-legacy#177]
The mac code no longer works for people that are running anything under High Sierra.
What sucks is, Apple had a glitch with installing high sierra so many people are not running it.
I believe it has something to do with the version of QT. It would be wise to support the people who used your wallet up until the change.

**Comment by nezero** [comment]
The official OSX builds we release are built on High Sierra, so we cannot guarantee that they will work on lower versions. Please build from source on if you wish to use it on an older version.

Just an FYI, the build machines will be upgraded to Mojave soon.

Also, please use the forums for queries like this, as this is not an issue with the code.
