### ISSUE TITLE
DeepOnion-cli does not compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by devzone777** [deeponion/deeponion-legacy#178]
Hi,

I have compiled many times but the cli daemon won't compile. How can I make the cli compile? I need it to do anything with the daemon. The DeepOnion-qt also doesn't work even though it did compile. Why not compile the daemons and put them in releases for download?

**Comment by devzone777** [comment]
Also there are no errors at all while compiling. Just get DeepOniond that does work, but no DeepOnion-cli and DeepOnion-qt aborts and exits immediately

**Comment by aitorp6** [comment]
With this version you don't need **DeepOnion-cli**, you can do everything with **DeepOniond**. Try for example:` DeepOniond help`

what's your problem with qt client? I can compile and execute it with out any problems.
