### ISSUE TITLE
The repository passes distrust

### ISSUE THREAD

**Issue by rodrigoslayertech** [deeponion/deeponion-legacy#19]
"No description, website, or topics provided. "
No wiki
No tutorial for build
Only 9 contributors
0 Releases

This repository passes distrust
Any news of when to update this metadata?

**Comment by brakmic** [comment]
Please, do not misuse GitHub's instruments to post polemics. GitHub is a strictly technical platform. Any other questions, especially polemic ones, have no place here. Use [our forums](https://deeponion.org/community/) for questions of that kind.

Thanks for your understanding.
