### ISSUE TITLE
src/db.h:14:20: fatal error: db_cxx.h: No such file or directory

### ISSUE THREAD

**Issue by dpblnt** [deeponion/deeponion-legacy#22]
In file included from src/db.h:8:0,
                 from src/smessage.h:11,
                 from src/qt/messagemodel.h:8,
                 from src/qt/bitcoin.cpp:8:
src/main.h:631:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         str += strprintf("(hash=%s, nTime=%d, ver=%d, vin.size=%"PRIszu", vout.size=%"PRIszu", nLockTime=%d)\n",
                          ^
src/main.h:631:72: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         str += strprintf("(hash=%s, nTime=%d, ver=%d, vin.size=%"PRIszu", vout.size=%"PRIszu", nLockTime=%d)\n",
                                                                        ^
src/main.h:1049:10: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   printf("CBlock(hash=%s, ver=%d, hashPrevBlock=%s, hashMerkleRoot=%s, nTime=%u, nBits=%08x, nNonce=%u, vtx=%"PRIszu", vchBlockSig=%s)\n",
          ^
src/main.h:1310:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         return strprintf("CBlockIndex(nprev=%p, pnext=%p, nFile=%u, nBlockPos=%-6d nHeight=%d, nMint=%s, nMoneySupply=%s, nFlags=(%s)(%d)(%s), nStakeModifier=%016"PRIx64", nStakeModifierChecksum=%08x, hashProofOfStake=%s, prevoutStake=(%s), nStakeTime=%d merkle=%s, hashBlock=%s)",
                          ^
In file included from src/smessage.h:11:0,
                 from src/qt/messagemodel.h:8,
                 from src/qt/bitcoin.cpp:8:
src/db.h:14:20: fatal error: db_cxx.h: No such file or directory
 #include <db_cxx.h>
                    ^
compilation terminated.
make: *** [Makefile:3325: build/bitcoin.o] Error 1

**Comment by dpblnt** [comment]
I do have 
equery u sys-libs/db
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-libs/db-5.3.28-r2:
 U I
 + + abi_x86_32 : 32-bit (x86) libraries
 + + cxx        : Build support for C++ (bindings, extra libraries, code generation, ...)
 - - doc        : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of
                  globally
 - - examples   : Install examples, usually source code
 - - java       : Add support for Java
 - - tcl        : Add support the Tcl language
 - - test       : Workaround to pull in packages needed to run with FEATURES=test. Portage-2.1.2 handles this
                  internally, so don't set it in make.conf/package.use anymore

equery u =sys-libs/db-4.8.30-r2
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-libs/db-4.8.30-r2:
 U I
 + + abi_x86_32 : 32-bit (x86) libraries
 + + cxx        : Build support for C++ (bindings, extra libraries, code generation, ...)
 - - doc        : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of
                  globally
 - - examples   : Install examples, usually source code
 - - java       : Add support for Java
 - - tcl        : Add support the Tcl language
 - - test       : Workaround to pull in packages needed to run with FEATURES=test. Portage-2.1.2 handles this
                  internally, so don't set it in make.conf/package.use anymore



and I do have the file on my system:
qlist sys-libs/db|grep db_cxx.h
/usr/include/db4.8/db_cxx.h
/usr/include/db5.3/db_cxx.h

**Comment by dpblnt** [comment]
had to add -I/usr/include/db5.3/ to INCPATH in  Makefile line 16

**Comment by dpblnt** [comment]
But then I get link error:

g++: error: deeponion/src/leveldb/libleveldb.a: No such file or directory
g++: error: deeponion/src/leveldb/libmemenv.a: No such file or directory
make: *** [Makefile:515: DeepOnion-qt] Error 1

**Comment by deeponion** [comment]
please try with autotools, it should be smooth now.
