### ISSUE TITLE
src/net.cpp:1008:74: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’

### ISSUE THREAD

**Issue by dpblnt** [deeponion/deeponion-legacy#23]
src/net.cpp:612:5: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
src/net.cpp:612:5: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
src/net.cpp: In function ‘void ThreadMapPort2(void*)’:
src/net.cpp:1008:68: warning: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                    ^~~~~~
src/net.cpp:1008:74: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                          ^
In file included from src/net.cpp:19:0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: declared here
 upnpDiscover(int delay, const char * multicastif,
 ^~~~~~~~~~~~
make: *** [Makefile:4287: build/net.o] Error 1

**Comment by dpblnt** [comment]
I have net-libs/miniupnpc-2.0.20170509

**Comment by dpblnt** [comment]
added new argument "0"  - as unsigned char ttl
in file src/net.cpp:1008

**Comment by 7hegrey** [comment]
Thanks for reporting and coming with solutions!
I hope there will be some updates soon, I know there is lots of work done, but not all of it is added to Github yet.
I'm not a c++ dev, but this patch looks like same as your solution, and may help others:
https://github.com/bitcoin/bitcoin/commit/9f3e48e5219a09b5ddfd6883d1f0498910eff4b6.patch

**Comment by deeponion** [comment]
thanks.
