### ISSUE TITLE
cant disable UPNP 

### ISSUE THREAD

**Issue by dpblnt** [deeponion/deeponion-legacy#24]
$ qmake "USE_UPNP=-"
Project MESSAGE: Building with QRCode support
Project MESSAGE: Building with UPNP support
Project MESSAGE: Building with IPv6 support
Project MESSAGE: Building with QRCode supportProject MESSAGE: Building with UPNP supportProject MESSAGE: Building with IPv6 support

while the documentation said:
| USE_UPNP=- | no UPnP support, miniupnpc not required;                                 |

**Comment by 7hegrey** [comment]
Looks like there is an override here, making upnp required and enabled:
https://github.com/deeponion/deeponion/blob/master/DeepOnion-qt.pro#L108

**Comment by brakmic** [comment]
thread inactive. closed!
