### ISSUE TITLE
g++: error:deeponion/src/leveldb/libmemenv.a: No such file or directory

### ISSUE THREAD

**Issue by dpblnt** [deeponion/deeponion-legacy#25]
make: *** [Makefile:515: DeepOnion-qt] Error 1

$ find . |grep libmemenv
[no output]

$ find . |grep memenv
./src/leveldb/helpers/memenv
./src/leveldb/helpers/memenv/memenv.cc
./src/leveldb/helpers/memenv/.gitignore
./src/leveldb/helpers/memenv/memenv_test.cc
./src/leveldb/helpers/memenv/memenv.h

nothing has been  built there

**Comment by dpblnt** [comment]
had to do this by hand:
cd src/leveldb/
make libleveldb.a libmemenv.a;
then continue the make in ../../

**Comment by deeponion** [comment]
yes you need to build manually now, we'll fix the script soon.

**Comment by brakmic** [comment]
@dpblnt 

As @deeponion already wrote, there's a single manual step needed to build leveldb. Soon we'll provide a complete tutorial on how to build the wallet from scratch.

**Comment by typoworx-de** [comment]
did you try this? Note the "--recursive" flag!
https://github.com/deeponion/deeponion/blob/master/doc/build-unix.txt#L32

`git clone --recursive https://github.com/deeponion/deeponion.git
`

**Comment by brakmic** [comment]
thread inactive. closed!
