### ISSUE TITLE
undefined reference to 'tor_main'

### ISSUE THREAD

**Issue by ghost** [deeponion/deeponion-legacy#28]
Hello,

I'm building the wallet on a clean ubuntu vm, getting this error:

`Putting child 0xc42a30 (DeepOnion-qt) PID 2890 on the chain.
Live child 0xc42a30 (DeepOnion-qt) PID 2890
build/net.o: In function `ThreadTorNet2(void*)':
net.cpp:(.text+0x6e45): undefined reference to `tor_main'
collect2: error: ld returned 1 exit status
Reaping losing child 0xc42a30 PID 2890
Makefile:607: recipe for target 'DeepOnion-qt' failed
make: *** [DeepOnion-qt] Error 1
Removing child 0xc42a30 PID 2890 from chain.`

searched in some older and newer "how to build deeponion on ubuntu" guides, but haven't been able to track down if it's my system

**Comment by brakmic** [comment]
*tor_main* is an external function provided via tor sources. If you checkout our sources you'll have everything that's needed inside the *tor* directory.

Just to be sure you have them, which btw. we reference as a **git submodule**, please execute the following command in your shell:

`git submodule update --init`

Then do

*  `./autogen.sh`
* `./configure --disable-tests --with-gui=qt5`   => or any other flags you prefer
* `make`

**Comment by deeponion** [comment]
When you do git clone, use recursive flag so you'll get all content in tor dir, then run autotool:

git clone --recursive https://github.com/deeponion/deeponion
./autogen.sh
./configure --with-gui=qt5
./make
