### ISSUE TITLE
Zero balance after importprivkey

### ISSUE THREAD

**Issue by vith27** [deeponion/deeponion-legacy#30]
Hello,
I installed the MacOS DO desktop wallet and try multiple times to import a private key from paper wallet with some onions into (500). Each time the import was done, but wallet show me zero balance. The wallet appears in the "addresses" tab.
I moved some onions (91) from exchange to the same wallet address after the private key was imported, and now the desktop wallet show me only the moved onions (91), not the whole wallet funds (591). Is there a bug with the importprivkey command on MacOS ?

I explained the problem on this thread: https://deeponion.org/community/threads/my-computer-wallet-showing-zero-balance.23151/

Thanks in advance for any suggestion.

**Comment by brakmic** [comment]
Hi, 

Please **do not use** GitHub for user-related problems. For such problems use our community pages (forums etc.). There are many people who have enough experience and time to help you solve such problems. And it also makes little sense to report the same problem over different channels. This will surely _not_ help you get rid of the problem sooner.

GitHub is a specialized **platform for developers** and those who help us **to improve our software**. 
You are not helping us by opening issues that only describe some individual problem without any deeper information (log-files, error reports, or maybe code examples).

Thank you for your understanding,

**Comment by vith27** [comment]
Brakmic, thank you for your reply.

I wrote here because no one could help me on this problem and several people suspect it's a bug with the macos version. The only way I see to get it working is to import my whole paper wallet to an exchange that allow it for DO and resend the whole amount to my wallet. It seems strange to do that... But if you cannot consider this problem as a bug I'm not in the right place, ok...

Sorry for inconvenience.

Best regards and thanks for your job :)
