### ISSUE TITLE
error: undefined reference to `tor_main'

### ISSUE THREAD

**Issue by HELLKING66666** [deeponion/deeponion-legacy#33]
From deeponion forum tutorial, I had installed the dependency within Ubuntu 16.04.

**Comment by HELLKING66666** [comment]
build/net.o：In function ‘ThreadTorNet2(void*)’中：
net.cpp:(.text+0x6e45)：undefined reference to ‘tor_main’
collect2: error: ld returned 1 exit status
Makefile:603: recipe for target 'DeepOnion-qt' failed
make: *** [DeepOnion-qt] Error 1

**Comment by deeponion** [comment]
You need to get the repo recursively and do the build. Apparently you did not build the tor. Follow the instructions here:
https://github.com/deeponion/deeponion/blob/master/doc/build-unix.txt

**Comment by HELLKING66666** [comment]
compat_libevent.c:(.text+0x890)：undefined reference to  ‘event_base_update_cache_time’
collect2: error: ld returned 1 exit status
Makefile:1755: recipe for target 'qt/DeepOnion-qt' failed
make[1]: *** [qt/DeepOnion-qt] Error 1
make[1]: Leaving directory '/home/hellking/Desktop/Repo/deeponion/src'
Makefile:536: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1


------------------------------------
How to fix that?

**Comment by HELLKING66666** [comment]
Just follow the commands in build-unix.txt, but not found the command to build the tor, should it built alone?

**Comment by deeponion** [comment]
did you do "--recursive" when you clone the repo? do you see anything in the tor dir? if so and if your autogen and configure are successful, then there's no problem at all in build. Just follow strictly the instructions. The tor is built as the first part of the make:
...
config.status: creating src/config/deeponion-config.h
config.status: executing depfiles commands
root@30006:~/test/deeponion# make
Making all in tor
make[1]: Entering directory '/root/test/deeponion/tor'
make  all-am
make[2]: Entering directory '/root/test/deeponion/tor'
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_0.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_1.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_add.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_cmov.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_copy.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_frombytes.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_invert.o
  CC       src/ext/ed25519/ref10/src_ext_ed25519_ref10_libed25519_ref10_a-fe_isnegative.o
...

**Comment by HELLKING66666** [comment]
Thanks for your kind helping.

------------------------------
Here is my ./autogen.sh output
-----------------------------
为 'tor' 同步子模组 url
为 'tor/src/ext/rust' 同步子模组 url
子模组路径 'tor'：检出 '48a51c5f8b80a359da31bc5aaac8ecd25890fe0d'
子模组路径 'tor/src/ext/rust'：检出 '240296800824e40b10cb8c16da0e711563353945'
~/Desktop/Repo/deeponion/tor ~/Desktop/Repo/deeponion
~/Desktop/Repo/deeponion
configure.ac:718: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
configure.ac:718: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
~/Desktop/Repo/deeponion/tor ~/Desktop/Repo/deeponion
patching file src/or/include.am
Hunk #2 succeeded at 104 (offset 4 lines).
patching file src/include.am
configure.ac:230: installing './ar-lib'
configure.ac:19: installing './compile'
configure.ac:20: installing './config.guess'
configure.ac:20: installing './config.sub'
configure.ac:14: installing './install-sh'
configure.ac:14: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
~/Desktop/Repo/deeponion

----------------------------
./configure --with-gui=qt5 output
----------------------------
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Doxyfile
config.status: creating Makefile
config.status: creating contrib/dist/suse/tor.sh
config.status: creating contrib/operator-tools/tor.logrotate
config.status: creating contrib/dist/tor.sh
config.status: creating contrib/dist/torctl
config.status: creating contrib/dist/tor.service
config.status: creating src/config/torrc.sample
config.status: creating src/config/torrc.minimal
config.status: creating src/rust/.cargo/config
config.status: creating scripts/maint/checkOptionDocs.pl
config.status: creating scripts/maint/updateVersions.pl
config.status: creating orconfig.h
config.status: executing depfiles commands
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating share/setup.nsi
config.status: creating share/qt/Info.plist
config.status: creating qa/pull-tester/run-bitcoind-for-test.sh
config.status: creating qa/pull-tester/build-tests.sh
config.status: creating src/config/deeponion-config.h
config.status: executing depfiles commands



Yeah the tor is compiled first.At last, compilation still failed.
make[2]: Leaving directory '/home/hellking/Desktop/Repo/deeponion/src/leveldb'
  CXXLD    DeepOniond
  CXX      qt/qt_DeepOnion_qt-bitcoin.o
  OBJCXXLD qt/DeepOnion-qt
../tor/src/common/libor-event.a(compat_libevent.o)：在函数‘tor_gettimeofday_cache_clear’中：
compat_libevent.c:(.text+0x890)：对‘event_base_update_cache_time’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:1755: recipe for target 'qt/DeepOnion-qt' failed
make[1]: *** [qt/DeepOnion-qt] Error 1
make[1]: Leaving directory '/home/hellking/Desktop/Repo/deeponion/src'
Makefile:536: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by deeponion** [comment]
this is weird, I don't see this issue... my compile on ubuntu 16.04 is very smooth:
...
/usr/bin/ar: creating libleveldb.a
make[2]: Leaving directory '/root/test/deeponion/src/leveldb'
  CXXLD    DeepOniond
  CXX      qt/qt_DeepOnion_qt-bitcoin.o
  OBJCXXLD qt/DeepOnion-qt
make[1]: Leaving directory '/root/test/deeponion/src'
make[1]: Entering directory '/root/test/deeponion'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/test/deeponion'

what's your compiler version? gcc -v, g++ -v?

**Comment by brakmic** [comment]
You seem to have a problem with libevent. 

**apt-get install libevent-dev**

**Comment by HELLKING66666** [comment]
Before Compilation, I compiled latest version of some dependency like miniupnpc(2.0), libevent(2.1.8) but i dont think it matters, i strongly follow the compilation documents.My kernel version is 4.13.0-17-generic

**Comment by brakmic** [comment]
You should compile the *correct* versions, not latest ones.

**Comment by HELLKING66666** [comment]
libevent-dev  (2.0.21-stable-2ubuntu0.16.04.1)

**Comment by brakmic** [comment]
Also install libevent itself, as it needs the above function *event_base_update_cache_time*

**apt get install libevent**

**Comment by brakmic** [comment]
Hm, something seems to be wrong here, as the export function is not visible. First, my assumption was that it's because of wrong packages (with or without the 2 in the name) but this only affects non-Ubuntu distros. 
Have just checked it again.

**Comment by HELLKING66666** [comment]
Ah, libevent and libevent-dev are 2.0.21-stable-2ubuntu0.16.04.1 from The Xenial Xerus apt-repository

**Comment by brakmic** [comment]
Could you open your generated src/Makefile and search for **-levent** flag. It should look like this

**LIBEVENT_LIBS = -levent**

**Comment by brakmic** [comment]
Does it work now?

**Comment by HELLKING66666** [comment]
grep -i 'levent' Makefile
Output:
LIBEVENT_LIBS = -L/usr/local/lib -levent


Sorry, still not work yet

**Comment by brakmic** [comment]
Does your /usr/local/lib contain a **libevent.so** file?

**Comment by HELLKING66666** [comment]
Yeah but it's version seems to be 2.1

**Comment by HELLKING66666** [comment]
lrwxrwxrwx 1 root root 21 1月  23 17:29 /usr/local/lib/libevent.so -> libevent-2.1.so.6.0.2*

**Comment by brakmic** [comment]
Well, maybe it's better for you to cleanup all that libs first. Otherweise you'll simply lose to much time estimating what the problem could be. I'd simply clean up everything, remove all the library cruft and start over. The few google search entries regarding similar problems all had to do with broken lib-paths & versions. It doesn't have to be your fault, but to miss a library or get a wrong version is (sadly) something very *normal* in Linux circles.

**Comment by HELLKING66666** [comment]
1. apt-get purge libqrencode-dev libminiupnpc-dev libevent-dev libcap-dev libseccomp-dev... etc
2. rm -rf /usr/lib/lib*** && rm -rf /usr/local/lib/lib*****
3. Follow the installation document.

I am taking a try. Thanks a lot. Hope it will be fixed

**Comment by brakmic** [comment]
👍 

Let us know what the problem was, so we can help others avoid it.

**Comment by HELLKING66666** [comment]
I find out that the lib path was /usr/lib/x86_64**** via apt-get installation.

Should I modify some env?

**Comment by HELLKING66666** [comment]
I have downloaded the version 2.0.21 libevent from libevent.org which is the same of ubuntu apt-repository. Changed the makefile -levent path and include path. Still didnt work.


Configure for libevent check
-----------
checking for libevent directory... (system)
checking whether we need extra options to link libevent... (none)
checking event2/event.h usability... yes
checking event2/event.h presence... yes
checking for event2/event.h... yes
checking event2/dns.h usability... yes
checking event2/dns.h presence... yes
checking for event2/dns.h... yes
checking event2/bufferevent_ssl.h usability... yes
checking event2/bufferevent_ssl.h presence... yes
checking for event2/bufferevent_ssl.h... yes
checking for library containing event_new... -levent
checking for library containing evdns_base_new... none required
checking for evutil_secure_rng_set_urandom_device_file... no
checking for evutil_secure_rng_add_bytes... yes
checking whether Libevent is new enough... yes

#### Still Error
----
../tor/src/common/libor-event.a(compat_libevent.o)：在函数‘tor_gettimeofday_cache_clear’中：
compat_libevent.c:(.text+0x890)：对‘event_base_update_cache_time’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:1735: recipe for target 'DeepOniond' failed
make[1]: *** [DeepOniond] Error 1
make[1]: Leaving directory '/home/hellking/Desktop/Repo/deeponion/src'
Makefile:536: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by HELLKING66666** [comment]
Now I found that only libevent 2.1.8-stable version has the function called ‘event_base_update_cache_time’. I compiled it manually, export the LIBEVENT_CFLAGS and LIB at the **/deeponion, but the tor project seems to compile error compat_libevent.o caused by not correct include or lib path......:(    :( 

Still Error

**Comment by brakmic** [comment]
Well, this error goes beyond the *usual* ones. Maybe you could try to checkout one of the branches I'm currently working on?

**git clone --recursive https://github.com/brakmic/deeponion.git -b integrate-leveldb**

The code is the same like in the official version, only the submodule structure is different (here *leveldb* is a submodule too).

If you're brave enough try to compile it. If it fails again, then you have some real problems with the libraries/headers on your machine. If not, well, you'll have a working wallet. 

I know, it's not *the correct solution* for your problem, but before I start to read the Crystall Ball and we run into further problems, maybe the best strategy is to leave the configuration on your machine and try an alternative.

**Comment by HELLKING66666** [comment]
Still Error. :( , I give up.
But thanks a lot for helping.
