### ISSUE TITLE
./DeepOniond: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by eddieadams** [deeponion/deeponion-legacy#4]
./DeepOniond: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

**Comment by niklasmato** [comment]
you might try to install following libraries : 

libboost-system1.55-dev - Operating system (e.g. diagnostics support) library
libboost-system1.55.0 - Operating system (e.g. diagnostics support) library

**Comment by deeponion** [comment]
looks like linux version should be compiled with static libraries, otherwise there are too many dependencies. We will fix it in next linux release. Thanks.

**Comment by deeponion** [comment]
we fix the issue by using autotools for build. Now everything should be smooth.
