### ISSUE TITLE
Show QR Code not working, no options highlighting

### ISSUE THREAD

**Issue by dragononcrypto** [deeponion/deeponion-legacy#44]
On Lubuntu 17.10, build v1.5.1:

When right clicking on a receiving address and selecting the "Show QR Code" option then nothing happens. Maybe you already know about this but thought I'd mention if not.

Also when hovering the mouse over the options of a receiving address _(Copy Address, Copy Lablel, Edit, Show QR Code, Sign Message)_ no options are highlighted. Ie the option isn't highlighted in a different colour, although all other options are functional. This isn't a bug but thought it'd be worth mentioning too.

Hope that helps. Other than that it's all working perfectly. Great job!

**Comment by deeponion** [comment]
which wallet you use? On my windows wallet (1.5.0-DV) it works fine, the QR code display OK. see attached screenshot 
![capture](https://user-images.githubusercontent.com/30008032/35639722-f6892604-066f-11e8-9e26-f3082734c80e.JPG)

**Comment by deeponion** [comment]
Oh I see you said Ubuntu 17.10, will check,, thanks.

**Comment by dragononcrypto** [comment]
Just checked it in other QT wallets and doesn't work either, should of done that before!
QT problem not DeepOnion, closed.
