### ISSUE TITLE
Build fails missing '../tor/src/or/libtor.a'

### ISSUE THREAD

**Issue by typoworx-de** [deeponion/deeponion-legacy#47]
`make: *** No rule to make target '../tor/src/or/libtor.a', needed by 'DeepOniond'.  Stop.`

Already tried building tor manually before, but didn't solve this.

**Comment by brakmic** [comment]
What OS?
When you report problems, please, take into account that we neither do telepathy nor use Crystal Balls.

**Comment by typoworx-de** [comment]
Ubuntu Linux (16.04 Xenial)
Regarding to TorProject-Sources the missing file is on gitignore there?
https://github.com/torproject/tor/blob/master/.gitignore#L174

**Comment by brakmic** [comment]
Under linux you compile your sources. Under Windows there are prepared libs under dir "torlibs-win". In your case I assume you have cloned the project with --recursive flag. The gitignore stuff is of no interest to you as you are not changing our source tree.

Just follow the docs: https://github.com/deeponion/deeponion/blob/master/doc/build-unix.txt

**Comment by typoworx-de** [comment]
I need to compile from source as precompiled download of deeponion is not fully static compiled and needs more recent libboost-system than provided by ubuntu/xenial.

`usr/bin/DeepOniond: error while loading shared libraries: libboost_system.so.1.64.0: cannot open shared object file: No such file or directory`

**Comment by brakmic** [comment]
What you have on your local system is up to you. What we use for our project is our decision. If you want to integrate a newer version of a library, because you think you know better, then please do not open a issue here.  This is not an issue that affects all users but only you, because you are imposing your own rules. You have any right to do so on your system, but not for other users.

**Comment by typoworx-de** [comment]
Thats fine. But if you provide Linux-Wallet it should work on most linux-versions and not only any more recent/beta versions providing newer libs. A linux-wallet working only on a hand-full of linux-dist is more or less useless especially if compile from source also has such blockers.
One possible solution would to compile full-static version including all depends inside the binary.

I'm used to compile most wallets I'm interested in from source to make shure it's a clean and compatible version for my system. I compiled more than 15 different wallets and this is the first one lacking such a problem that doesn't seem to be solvable neither by community-help nor the project-owners.

**Comment by typoworx-de** [comment]
Just to make it clear... I'm not using a newer version of the libboost_system.so! You do so in precompiled binary.

DeepOnion binary-build requires libboost_system.so.**1.64.0**.so. On Ubuntu Xenial with latest updates there only is libboost-system**1.58.0**.so. I think most debian-dist (even the current/LTS) does not even provide such new versions Ubuntu does. In most cases software/libs on debian are a little bit more decent!

**Comment by typoworx-de** [comment]
Here's a dump for Debian and Ubuntu of most recent Libboost-System Versions:

1. Debian ("Stretch") has only libboost-system1.62.0
2. Ubuntu ("Arty" is still not LTS/long-term-support) has only libboost-system1.63.0

-------
1. https://packages.debian.org/search?keywords=libboost-system&searchon=names&suite=stable&section=all
2. https://packages.ubuntu.com/search?keywords=libboost-system&searchon=names&suite=artful&section=all

**Comment by brakmic** [comment]
Thank you. We'll take your inputs and look into the issue.

**Comment by typoworx-de** [comment]
ok thank you

**Comment by dragononcrypto** [comment]
If you still want to build then there is the option of [symlinks documented](https://deeponion.org/community/threads/tutorial-installing-deeponion-v1-5-1-on-ubuntu-debian.28202/) to get around this problem, that has been the case for months... I've otherwise built it no problem in Ubuntu 16.04.03 with default 1.58.0.so and 17.10 with default **[1.62.0.so](https://packages.ubuntu.com/artful/libboost-all-dev)** libraries (not 1.63.0 btw). So I'm not convinced _"DeepOnion binary-build requires libboost_system.so.1.62.0.so. "_.
Furthermore when upgrading from 16.04 to 17.10 (with no clean install) I was then (unsurprisingly) lacking **1.58.0.so**, not 1.62.0.so as you suggest.

**Comment by brakmic** [comment]
Boost libraries can be built independently, regardless of distro. I doubt one couldn't build any of their versions for own distros. Even in such cases when a certain version is missing for a particular distro. However, we will make this stuff more general, so that our users don't have to build anything anyway. I've forwarded your issue and soon we'll have a solution for it.

**Comment by typoworx-de** [comment]
The build-problem is not because of libboost-system. This only is for the binary-build provided by the project.

My source-build got stuck here:
`make: *** No rule to make target '../tor/src/or/libtor.a', needed by 'DeepOniond'. Stop.`

Even trying to separately pre-build tor sources doesn't provide the given library out of tor-sources. That file simply doesn't exist - but ../tor/src/ is present.

**Comment by typoworx-de** [comment]
@dragononcrypto I also gave the "hacky" symlink solution a try... $> ldd DeepOniond doesn't complain about missing libs anymore. But trying to start throws this:

```
./DeepOniond
./DeepOniond: symbol lookup error: ./DeepOniond: undefined symbol: _ZN5boost11this_thread6hidden9sleep_forERK8timespec
```
The symlined boost-libs between (in my case) version 1.58 and required 1.64 (static build of deeponion) does not look compatible.

**Comment by brakmic** [comment]
The issue with "src/libtor.a" looks very suspicious as there isn't a "src/libtor.a" but only the usual "src/or/libtor.a" (the onion router, hence "or" in the path). I'll forward this info for further tests. Actually, I should have spotted it at the beginning but the issue with boost libs distracted me. ;)
I think there are two distinct issues here which we will investigate asap.

Thanks again.

**Comment by brakmic** [comment]
Ah, you have the correct path, I see. Then the issue isn't the path but somehow the lib can't be found there.

**Comment by brakmic** [comment]
One question: the make issue with torlib.a happens when you execute the usual autogen.sh, configure, make?

**Comment by typoworx-de** [comment]
Call me crazy... I don't know why but now it has been working @brakmic!!! I deleted everything and did another fresh checkout:

$> git clone --recursive https://github.com/deeponion/deeponion.git

and then it compiled. Don't know what could have been wrong last try.

**Comment by typoworx-de** [comment]
Never the less... It would be nice to have a pre-compiled version that includes the required so-libs.

**Comment by brakmic** [comment]
Well, I don't know either. 😄 
But what counts now is that you have a working build.
One explanation might be that you maybe had some older version or some files were not up to date. 

Have fun with DeepOnion!

**Comment by brakmic** [comment]
Regarding the precompiled version, I forwarded all of your info and colleagues are working on it.

**Comment by typoworx-de** [comment]
Thank you very much for any help!
