### ISSUE TITLE
Error compiling in Ubuntu 16.04

### ISSUE THREAD

**Issue by cezar1** [deeponion/deeponion-legacy#49]
I did:
git clone https://github.com/deeponion/deeponion.git --recursive
cd deeponion
./autogen.sh
./configure

I get :
configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore)

How can I point the Berkeley DB to the correct location for autotools?

**Comment by brakmic** [comment]
The **Issues Section** is not for helping users configure their systems. And regarding the problem with Berkeley DB a simple Google Search would deliver enough information. 

Here is [one of the many methods](https://github.com/bitcoin/bitcoin/blob/0.9/doc/build-unix.md#berkeley-db) for manual compilation of BDB.

In future, please, only post issues that affect our software, not your local configuration problems.

Thanks!

**Comment by dragononcrypto** [comment]
More specifically in Ubuntu 16.04 you install from repository, as per the [build instructions](https://github.com/deeponion/deeponion/blob/master/doc/build-unix.txt):
<code>sudo add-apt-repository ppa:bitcoin/bitcoin</code>
<code>sudo apt update</code>
<code>sudo apt install ibdb4.8-dev libdb4.8++-dev</code>

**Comment by deeponion** [comment]
yes install berkeley DB as per instruction you should be fine.

**Comment by cezar1** [comment]
Thanks for all the help. it is indeed a local configuration problem.

What I had to do was give some extra params to configure:

./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib" --with-gui=qt5

**Comment by deeponion** [comment]
I see, looks like you installed Berkeley DB in a different location. If you follow strictly the guide, it should be in the def location. Glad you solved the issue.
