### ISSUE TITLE
Please provide Mac and Linux binaries for download

### ISSUE THREAD

**Issue by probonopd** [deeponion/deeponion-legacy#58]
(Continued from https://github.com/deeponion/deeponion/pull/57)

Please provide binaries for download on https://github.com/deeponion/deeponion/releases so that one can use your software without having to compile it yourself. Only providing source code and telling users "go compile yourself" is not user friendly and leads to less users trying your software.

**Comment by brakmic** [comment]
Please, do not misuse Issues area to teach us on how we should treat our users. Polemics don't help. 

Thanks!

**Comment by probonopd** [comment]
Sorry @brakmic but in no way I meant to be polemic. This is a honest feature request; something GitHub Issues are meant for. Please consider this feature request. Thanks.
