### ISSUE TITLE
Linux version misssing on downloads page

### ISSUE THREAD

**Issue by probonopd** [deeponion/deeponion-legacy#60]
The downloads page says it is available for Linux but I cannot find any download link for Linux:

![](https://user-images.githubusercontent.com/2480569/36061381-4d8272c4-0e51-11e8-953a-ebf8bda1663e.png)

**Comment by brakmic** [comment]
Currently source code only.

**Comment by probonopd** [comment]
Then the text

> Software is available for Windows, Mac, __and Linux__.

is wrong.
