### ISSUE TITLE
Please implement what 'build-appimage.md' describes

### ISSUE THREAD

**Issue by pdfkungfoo** [deeponion/deeponion-legacy#64]
In the 'doc' subdir there is a 'build-appimage.md' document which explains how to build an AppImage of deeponion.

Wouldn't it be a good idea to implement these exact instruction steps in a *`.travis.yml`* script and have an AppImage automatically built upon each commit ('continuous') or each tagged release ('release')?

Let me know if you need help with implementing this via Travis CI, and if you would be willing to accept a pull request for this.

**Comment by brakmic** [comment]
No enough resources, sorry. But some of our users have created them. 
Check out this thread:  

https://deeponion.org/community/threads/tutorial-packaging-deeponion-qt-wallet-with-appimage.29042/
