### ISSUE TITLE
Mac Wallet Issue (Low Priority)

### ISSUE THREAD

**Issue by ghost** [deeponion/deeponion-legacy#69]
> Hi,
> 
> Sorry I can't offer a more technical description, but I'm running the newest version of the wallet on an iMac and having a recurring problem. Launching the wallet is fine, and it will sync. Once it is synced, if I minimize the window back to the Dock, it continues to run but cannot ever be returned to the screen. What I mean is, if I click on the wallet icon on the dock, the tools appear at the top of the screen (menu buttons?) but the wallet interface does not appear on the desktop. In other words, I can see the icon, and see the controls at the very top, but not see the wallet.
> 
> The only solution is to close the wallet and re-launch.
> 
> I've tried waiting a while to see if it will re-appear, but time does not seem to be the issue.
> 
> I thought I would let you know. Keep up the good work!
---------------------------
> When I minimize the wallet it goes to the section that shows in my screenshot. Once I click on that icon the wallet appears.
> 
> Yes I also notice that on the app dock itself if I click on the DeepOnion wallet icon nothing happens. It minimizes differently than other ap
---------------------------
![screenshot](https://user-images.githubusercontent.com/37119460/37049793-d140642e-2150-11e8-9ac4-9519d01d2a09.png)

**Comment by nezero** [comment]
It's been a while since I've used the GUI wallet on a MAC, but from memory I think I had a similar issue (with all QT wallets on a MAC). If you right click ONION icon in the doc and select show all windows does it appear? I seem to remember that bringing the wallet into view.

**Comment by ghost** [comment]
Yes, correct. When you right-click the icon and select (Show All Windows) if you select the wallet it shows.

On other Mac software, I notice that by simply clicking the icon the app appears when minimized.

This is not a serious issue at all. I just wanted you guys to be aware in case you did not know about this.

**Comment by brakmic** [comment]
Here's a tutorial on how to build DeepOnion for Mac:

https://github.com/deeponion/deeponion/issues/76#issuecomment-374508739
