### ISSUE TITLE
macOS build architecture error

### ISSUE THREAD

**Issue by BKn0wn** [deeponion/deeponion-legacy#71]
Having issues when building DeepOnion-qt.pro

> `Undefined symbols for architecture x86_64:
>   "_TLS_method", referenced from:
>       _tor_tls_context_init_one in libor-crypto.a(tortls.o)
>       _tor_tls_classify_client_ciphers in libor-crypto.a(tortls.o)
>   "_evdns_add_server_port_with_base", referenced from:
>       _dnsserv_configure_listener in libtor.a(dnsserv.o)
>   "_evdns_base_clear_nameservers_and_suspend", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>       _dns_reset in libtor.a(dns.o)
>   "_evdns_base_count_nameservers", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>   "_evdns_base_new", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>       _dns_reset in libtor.a(dns.o)
>   "_evdns_base_resolv_conf_parse", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>   "_evdns_base_resolve_ipv4", referenced from:
>       _launch_one_resolve in libtor.a(dns.o)
>       _launch_wildcard_check in libtor.a(dns.o)
>   "_evdns_base_resolve_ipv6", referenced from:
>       _launch_one_resolve in libtor.a(dns.o)
>       _launch_wildcard_check in libtor.a(dns.o)
>   "_evdns_base_resolve_reverse", referenced from:
>       _launch_one_resolve in libtor.a(dns.o)
>   "_evdns_base_resolve_reverse_ipv6", referenced from:
>       _launch_one_resolve in libtor.a(dns.o)
>   "_evdns_base_resume", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>   "_evdns_base_search_clear", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>       _dns_reset in libtor.a(dns.o)
>   "_evdns_base_set_option", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>   "_evdns_close_server_port", referenced from:
>       _dnsserv_close_listener in libtor.a(dnsserv.o)
>   "_evdns_server_request_add_a_reply", referenced from:
>       _dnsserv_resolved in libtor.a(dnsserv.o)
>   "_evdns_server_request_add_aaaa_reply", referenced from:
>       _dnsserv_resolved in libtor.a(dnsserv.o)
>   "_evdns_server_request_add_ptr_reply", referenced from:
>       _dnsserv_resolved in libtor.a(dnsserv.o)
>   "_evdns_server_request_get_requesting_addr", referenced from:
>       _evdns_server_callback in libtor.a(dnsserv.o)
>   "_evdns_server_request_respond", referenced from:
>       _dnsserv_reject_request in libtor.a(dnsserv.o)
>       _dnsserv_resolved in libtor.a(dnsserv.o)
>       _evdns_server_callback in libtor.a(dnsserv.o)
>   "_evdns_set_log_fn", referenced from:
>       _configure_nameservers in libtor.a(dns.o)
>   "_evdns_set_random_bytes_fn", referenced from:
>       _dns_init in libtor.a(dns.o)
>   "_evdns_shutdown", referenced from:
>       _tor_free_all in libtor.a(main.o)
>   "_event_active", referenced from:
>       _directory_all_unreachable in libtor.a(main.o)
>       _do_main_loop in libtor.a(main.o)
>       _activate_signal in libtor.a(main.o)
>       _queue_control_event_string in libtor.a(control.o)
>       _scheduler_ev_active in libtor.a(scheduler.o)
>   "_event_add", referenced from:
>       _connection_start_reading in libtor.a(main.o)
>       _connection_start_writing in libtor.a(main.o)
>       _tor_shutdown_event_loop_and_exit in libtor.a(main.o)
>       _do_main_loop in libtor.a(main.o)
>       _handle_signals in libtor.a(main.o)
>       _signal_callback in libtor.a(main.o)
>       _check_ed_keys_callback in libtor.a(main.o)
>       ...
>      (maybe you meant: _control_event_address_mapped)
>   "_event_base_free", referenced from:
>       _tor_libevent_free_all in libor-event.a(compat_libevent.o)
>   "_event_base_get_method", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>       _tor_libevent_get_method in libor-event.a(compat_libevent.o)
>   "_event_base_gettimeofday_cached", referenced from:
>       _tor_gettimeofday_cached in libor-event.a(compat_libevent.o)
>   "_event_base_loop", referenced from:
>     _do_main_loop in libtor.a(main.o)
>   "_event_base_loopbreak", referenced from:
>       _tor_shutdown_event_loop_and_exit in libtor.a(main.o)
>       _signal_callback in libtor.a(main.o)
>       _check_ed_keys_callback in libtor.a(main.o)
>   "_event_base_loopexit", referenced from:
>       _connection_start_reading_from_linked_conn in libtor.a(main.o)
>       _tell_event_loop_to_run_external_code in libtor.a(main.o)
>   "_event_base_new_with_config", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>   "_event_base_update_cache_time", referenced from:
>       _tor_gettimeofday_cache_clear in libor-event.a(compat_libevent.o)
>   "_event_config_free", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>   "_event_config_new", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>   "_event_config_set_flag", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>   "_event_config_set_num_cpus_hint", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>   "_event_del", referenced from:
>       _connection_unregister_events in libtor.a(main.o)
>       _connection_stop_reading in libtor.a(main.o)
>       _connection_stop_writing in libtor.a(main.o)
>       _scheduler_free_all in libtor.a(scheduler.o)
>   "_event_free", referenced from:
>       _tor_event_free_ in libor-event.a(compat_libevent.o)
>       _periodic_timer_free_ in libor-event.a(compat_libevent.o)
>      (maybe you meant: _tor_event_free_)
>   "_event_get_version", referenced from:
>       _tor_libevent_initialize in libor-event.a(compat_libevent.o)
>       _tor_libevent_get_version_str in libor-event.a(compat_libevent.o)
>   "_event_new", referenced from:
>       _connection_add_impl in libtor.a(main.o)
>       _tor_shutdown_event_loop_and_exit in libtor.a(main.o)
>       _directory_all_unreachable in libtor.a(main.o)
>       _do_main_loop in libtor.a(main.o)
>       _handle_signals in libtor.a(main.o)
>       _signal_callback in libtor.a(main.o)
>       _check_ed_keys_callback in libtor.a(main.o)
>       ...
>      (maybe you meant: _control_event_newconsensus)
>   "_event_pending", referenced from:
>       _connection_is_reading in libtor.a(main.o)
>       _connection_is_writing in libtor.a(main.o)
>       _close_closeable_connections in libtor.a(main.o)
>   "_event_set_log_callback", referenced from:
>       _configure_libevent_logging in libor-event.a(compat_libevent.o)
>   "_evutil_secure_rng_add_bytes", referenced from:
>       _tor_init_libevent_rng in libor-event.a(compat_libevent.o)
>   "_evutil_secure_rng_get_bytes", referenced from:
>       _tor_init_libevent_rng in libor-event.a(compat_libevent.o)
>   "_evutil_secure_rng_init", referenced from:
>       _tor_init_libevent_rng in libor-event.a(compat_libevent.o)
>   "_evutil_secure_rng_set_urandom_device_file", referenced from:
>       _tor_run_main in libtor.a(main.o)
>   "_lzma_alone_decoder", referenced from:
>       _tor_lzma_compress_new in libor-crypto.a(compress_lzma.o)
>   "_lzma_alone_encoder", referenced from:
>       _tor_lzma_compress_new in libor-crypto.a(compress_lzma.o)
>   "_lzma_code", referenced from:
>       _tor_lzma_compress_process in libor-crypto.a(compress_lzma.o)
>   "_lzma_easy_decoder_memusage", referenced from:
>       _tor_lzma_compress_new in libor-crypto.a(compress_lzma.o)
>   "_lzma_easy_encoder_memusage", referenced from:
>      _tor_lzma_compress_new in libor-crypto.a(compress_lzma.o)
>   "_lzma_end", referenced from:
>       _tor_lzma_compress_free_ in libor-crypto.a(compress_lzma.o)
>   "_lzma_lzma_preset", referenced from:
>       _tor_lzma_compress_new in libor-crypto.a(compress_lzma.o)
>   "_lzma_version_string", referenced from:
>       _tor_lzma_get_version_str in libor-crypto.a(compress_lzma.o)
> ld: symbol(s) not found for architecture x86_64
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt] Error 1
>23:17:38: The process "/usr/bin/make" exited with code 2.
>Error while building/deploying project DeepOnion-qt (kit: Desktop Qt 5.7.1 clang 64bit)
>When executing step "Make"
>23:17:38: Elapsed time: 04:27.

Prior to posting, I tried compiling a separate tor directory in order to create the files under my system and linked them independently but still encounter the same undefined symbols for architecture.

Any help would be greatly appreciated!

**Comment by brakmic** [comment]
Not possible to build with Qt.pro files. 
But possible with autotools.
Look here: https://github.com/deeponion/deeponion/issues/76#issuecomment-374508739
