### ISSUE TITLE
Error compiling the second time

### ISSUE THREAD

**Issue by aitorp6** [deeponion/deeponion-legacy#75]
Hi.

I'm having some problems if I try to compile the wallet again. I have done 3 times and always I have the same problem and I don't know why (maybe is my fault)

The first time I do:
```
./autogen.sh
./configure --with-gui=qt5
make
```
and it compiles and works fine.

But I do the same a second time when I'm doing 'make' I get the following error:

```
 OBJCXXLD qt/DeepOnion-qt
qt/qt_DeepOnion_qt-bitcoin.o: In function `main':
/home/aitorp6/deeponion/src/qt/bitcoin.cpp:127: undefined reference to `qInitResources_bitcoin()'
collect2: error: ld returned 1 exit status
Makefile:2190: recipe for target 'qt/DeepOnion-qt' failed
make[1]: *** [qt/DeepOnion-qt] Error 1
make[1]: Leaving directory '/home/aitorp6/deeponion/src'
Makefile:536: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Any ideas?

I have tried doing:
```
make clean
./autogen.sh
./configure --with-gui=qt5
make
```

but still does not work.

**Comment by brakmic** [comment]
This is an error that happens from time to time although we have cleaned up the resource files. 
The last time I encountered it again I simply opened src/qt/bitcoin.qrc and src/qt/bitcoin_locale.qrc and typed a single space into it (just to make the file "changed"). Then I saved them both and tried to compile again. And it worked.

Also, those files should not have the entry pointing at this file: *locale/bitcoin_sc.qm*

If you find this file entry, please, remove it. Just delete the whole line. It's XML. There are some issues with Qt. It can't process the file but we don't know the reason in Qt. No visible errors.

**Comment by aitorp6** [comment]
Thank you for your response.
I'm translating the wallet into Spanish and when I wanted to compile it I had this issues. 

There is a entry pointing at that file (locale/bitcoin_sc.qm) here src/qt/bitcoin_locale.qrc  (https://github.com/deeponion/deeponion/blob/master/src/qt/bitcoin_locale.qrc). Maybe should be removed. 

On the other hand, do you know if anybody else is doing this translation? In order to avoid doing the same jobs two times...  


Thank you for your time and job

**Comment by brakmic** [comment]
Yes the doctype has to go. Actually, I removed it in a previous patch, but because we reverted a few patches for other reasons it could be that it came back. Will change it right now. Thanks!

**Comment by brakmic** [comment]
Have changed the resource files. 
Please, pull the latest changes.

**Comment by aitorp6** [comment]
Nice. 

In a couple of days I will have the Spanish translation ready. I will do pull request.

**Comment by chisNaN** [comment]
Sorry to bother again.
I tried the mentioned trick to change content file of `src/qt/bitcoin.qrc` and `src/qt/bitcoin_locale.qrc`
and i checked there is no `src/qt/locale/bitcoin_sc.qm`
before running the make command again
but still i have this slightly different error message (about x86_64 archi) at make command

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
  OBJCXXLD qt/DeepOnion-qt
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in DeepOnion_qt-bitcoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/DeepOnion-qt] Error 1
make: *** [all-recursive] Error 1
```

**Comment by aitorp6** [comment]
H @chisNaN 

Look at this, maybe it can help:

https://github.com/dmlc/xgboost/issues/1839

**Comment by chisNaN** [comment]
Thanks i will check and try ASAP

**Comment by chisNaN** [comment]
Here is what i did:

```
brew install gcc6 --without-multilib
cd deepnonion_install_dir/
make clean_all
```
first problem here: returns
`make: *** No rule to make target `clean_all'.  Stop.`

so i tried `make clean` instead followd by `make -j4`

and still the same error:

```
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in DeepOnion_qt-bitcoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/DeepOnion-qt] Error 1
make: *** [all-recursive] Error 1
```
I really would like to help because i am sure other people will face the same problem but this is not clear at all how to solve the problem and one has mainly to guess especially when a solution rises other problems...

**Comment by aitorp6** [comment]
I don't know where is the problem but I would try from a fresh downloaded code.

**Comment by chisNaN** [comment]
already tried that, thanks nevertheless

**Comment by nezero** [comment]
FYI - I've just worked around the issue by running this command

`touch src/qt/bitcoin.qrc`

I may get the make file to do it in the future.

**Comment by aitorp6** [comment]
It's a goo trick. Add it to the make file.

**Comment by chisNaN** [comment]
@nezero your command `touch` create the empty file if does not exist.
this `src/qt/bitcoin.qrc` already exists in my project and i added a space at the beginning of it.
What do you recommend in my case?
Thanks

**Comment by nezero** [comment]
Slightly confused about your comment. The command will modify the timestamp of the file so that the build tools think it has changed. That file is part of the source tree and will always exist, so if you type `make` and hit the error. run `touch src/qt/bitcoin.qrc; make` and it will build successfully.

There is a pull request that should fix this issue.
