### ISSUE TITLE
After compile i cant find DeepOniond (Ubuntu Server 16)

### ISSUE THREAD

**Issue by gggglglglg** [deeponion/deeponion-legacy#79]
**I did:**
git clone https://github.com/deeponion/deeponion.git --recursive
cd deeponion
./autogen.sh
./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib" --without-gui

**I get, last lines in terminal:**

>   CXX      leveldb/util/leveldb_libleveldb_a-logging.o
> leveldb/util/logging.cc: In function ‘bool leveldb::ConsumeDecimalNumber(leveldb::Slice*, uint64_t*)’:
> leveldb/util/logging.cc:58:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>            (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
>                                         ^
>   CXX      leveldb/util/leveldb_libleveldb_a-options.o
>   CXX      leveldb/util/leveldb_libleveldb_a-status.o
>   CXX      leveldb/port/leveldb_libleveldb_a-port_posix.o
>   AR       leveldb/libleveldb.a
> /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
>   CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
>   AR       leveldb/libmemenv.a
> /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
>   CXXLD    DeepOniond
> make[1]: Leaving directory '/home/admin/deeponion/src'
> make[1]: Entering directory '/home/admin/deeponion'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/admin/deeponion'

**There is no file "DeepOniond" in the folder "deeponion"**

**Comment by brakmic** [comment]
It's in **src/DeepOniond**
The UI is in **src/qt/DeepOnion-qt** (in case you do also a GUI build)

As stated in the Tutorial.
Please follow the tutorial and **READ IT THOROUGHLY** before reporting things that make no sense.
