### ISSUE TITLE
I installed on my mac, conf file missing it seems, i made one with new nodes still crashes

### ISSUE THREAD

**Issue by UnemployedRich** [deeponion/deeponion-legacy#80]
installed using the dmg file and the long way through terminal, it crashes after opening, i noticed i needed to add a .conf file so i did my best, one time it connected but the application crashes no matter what i do

**Comment by brakmic** [comment]
Please, do not use GitHub for user-support. Go to our forums. There are a plenty of tutorials, videos, and also **nice people** who are ready to help anyone. 

Your DeepOnion.conf must be put under /Users/your_user/Library/Application Support/DeepOnion

However, **visit** our forums before doing something you don't understand fully.
