### ISSUE TITLE
Compiling 1.6.3 on Ubuntu 17.10

### ISSUE THREAD

**Issue by jackrabbithanna** [deeponion/deeponion-legacy#89]
I've cloned the repo here, and checked out tags/v1.6.3
I follwed the instructions in ./docs/build-unix.txt exactly.. 
I am using an up to date Ubuntu 17.10 artful Linux version

Any ideas?

There's some error reporting in the 'make' step, all coming at the end:

make[1]: Entering directory '/opt/deeponion/src'
  CXX      libbitcoin_common_a-key.o
key.cpp: In function ‘int ECDSA_SIG_recover_key_GFp(EC_KEY*, ECDSA_SIG*, const unsigned char*, int, int, int)’:
key.cpp:81:28: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_add(x, x, ecsig->r)) { ret=-1; goto err; }
                            ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:81:30: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_add(x, x, ecsig->r)) { ret=-1; goto err; }
                              ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:102:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_inverse(rr, ecsig->r, order, ctx)) { ret=-1; goto err; }
                                  ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:102:36: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_inverse(rr, ecsig->r, order, ctx)) { ret=-1; goto err; }
                                    ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:104:31: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_mul(sor, ecsig->s, rr, order, ctx)) { ret=-1; goto err; }
                               ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:104:33: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_mul(sor, ecsig->s, rr, order, ctx)) { ret=-1; goto err; }
                                 ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp: In member function ‘bool CKey::Sign(uint256, std::vector<unsigned char>&)’:
key.cpp:358:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:358:21: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                     ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:360:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:360:21: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                     ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:360:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:360:36: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                    ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp: In member function ‘bool CKey::SignCompact(uint256, std::vector<unsigned char>&)’:
key.cpp:385:33: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     int nBitsR = BN_num_bits(sig->r);
                                 ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:385:35: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     int nBitsR = BN_num_bits(sig->r);
                                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:386:33: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     int nBitsS = BN_num_bits(sig->s);
                                 ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:386:35: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     int nBitsS = BN_num_bits(sig->s);
                                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:411:22: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_bn2bin(sig->r,&vchSig[33-(nBitsR+7)/8]);
                      ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:411:24: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_bn2bin(sig->r,&vchSig[33-(nBitsR+7)/8]);
                        ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:412:22: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_bn2bin(sig->s,&vchSig[65-(nBitsS+7)/8]);
                      ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:412:24: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_bn2bin(sig->s,&vchSig[65-(nBitsS+7)/8]);
                        ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp: In member function ‘bool CKey::SetCompactSignature(uint256, const std::vector<unsigned char>&)’:
key.cpp:431:32: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&vchSig[1],32,sig->r);
                                ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:431:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&vchSig[1],32,sig->r);
                                  ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:432:33: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&vchSig[33],32,sig->s);
                                 ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:432:35: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&vchSig[33],32,sig->s);
                                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:7:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
Makefile:3339: recipe for target 'libbitcoin_common_a-key.o' failed
make[1]: *** [libbitcoin_common_a-key.o] Error 1
make[1]: Leaving directory '/opt/deeponion/src'
Makefile:542: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by jackrabbithanna** [comment]
I have these packages related to openssl:
libcurl4-openssl-dev:amd64			install
libevent-openssl-2.1-6:amd64			install
libgnutls-openssl27:amd64			install
libio-socket-ssl-perl				install
libnet-smtp-ssl-perl				install
libnet-ssleay-perl				install
libssl-dev:amd64				install
libssl-doc					install
libssl1.0-dev:amd64				install
libssl1.0.0:amd64				install
libssl1.0.2:amd64				deinstall
libssl1.1:amd64					install
openssl

**Comment by brakmic** [comment]
Some openssl versions seem to have problems with certain ECDSA_sig_st types/structures. 
A quick fix is to replace the current *src/key.h* with this one we use in our *raspberry* branch. 

https://github.com/deeponion/deeponion/blob/raspberry/src/key.h

The only difference is this small struct:

```
struct ECDSA_SIG_st {
   BIGNUM *r;
   BIGNUM *s;
}
```

**Comment by jackrabbithanna** [comment]
Ok that seemed to work, it didn't seem to stop with an error, or at least it wasn't the same stuff...I didn't see what to run after that though, there didn't seem to be an executable file, so I tried  followed the instructions for compiling the Qt client

So I did:
 chmod +x ./src/leveldb/build_detect_platform
qmake
make

and it error's out with this:
collect2: error: ld returned 1 exit status
Makefile:634: recipe for target 'DeepOnion-qt' failed
make: *** [DeepOnion-qt] Error 1

**Comment by jackrabbithanna** [comment]
Would be neat if you guys could get a pre-compled version for Linux...I mean windows, mac, that's great....but how about a linux version so we don't all have to struggle to just have a DeepOnion wallet

**Comment by brakmic** [comment]
Not enough resources on our side. But luckily, there are users who have already done that work. 
Check this forum thread:

https://deeponion.org/community/threads/tutorial-packaging-deeponion-qt-wallet-with-appimage.29042/

**Comment by brakmic** [comment]
You should **NOT** use qmake but, [as stated in our docs](https://github.com/deeponion/deeponion/blob/master/doc/build-unix.md), the **autotools**.

So:

./autogen.sh
./configure --disable-tests --with-gui=qt5
make

**Comment by jackrabbithanna** [comment]
I did follow those instructions first....

I got the qmake etc.. from the doc/readme.rst

So basically I followed the instructions at first, and no executable were created that I could find. 
I had checked out the tag v1.6.3 but now I"m going to try with the master branch

Made sure I did all of this:
apt-get update
    apt-get upgrade
 apt-get install build-essential libtool autotools-dev autoconf automake pkg-config libssl-dev libboost-all-dev bsdmainutils
apt-get install libqrencode-dev libminiupnpc-dev libevent-dev libcap-dev libseccomp-dev git
apt-get install software-properties-common
add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install libdb4.8-dev libdb4.8++-dev
apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler

added the bit to the src/key.h
./autogen.sh
./configure -- with-gui=qt5
make

and it worked....

Thanks for your prompt help!

**Comment by brakmic** [comment]
Hm, this is an older doc I wasn't aware of. Sorry for the confusion. Will remove it.
Glad it now worked! 👍 

Have fun!
