### ISSUE TITLE
DeepOnion-Qt cannot be opened because of a problem.

### ISSUE THREAD

**Issue by nilathj** [deeponion/deeponion-legacy#95]
Hi, when I try to open up the latest DeepOnion I get an error.

Process:               DeepOnion-Qt [14876]
Path:                  /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
Identifier:            org.deeponion.DeepOnion-Qt
Version:               1.6.2 (1.6.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DeepOnion-Qt [14876]
User ID:               501

Date/Time:             2018-04-20 20:52:56.591 +1000
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        E13302FA-A969-660A-B213-0FE106AFF0F3

Sleep/Wake UUID:       4CE364B5-E0C6-4968-AE77-706619B54F3C

Time Awake Since Boot: 96000 seconds
Time Since Wake:       690 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
  Reason: image not found

Binary Images:
       0x1011c6000 -        0x1018e8fff +org.deeponion.DeepOnion-Qt (1.6.2 - 1.6.2) <ACC84206-56D4-3CFC-8D57-8B027F1361A7> /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
       0x1019f1000 -        0x1019f3ff7 +libboost_system.dylib (0) <5CFD618D-2AF4-3C59-88C2-B0CE6CCA7265> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x1019f8000 -        0x101a06fff +libboost_filesystem.dylib (0) <E0F26994-D113-3440-9645-6E4FB91ABF19> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x101a0e000 -        0x101a3efff +libboost_program_options-mt.dylib (0) <4280CB1D-C6B9-350D-B89E-5BBFFEBE8896> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x101a5b000 -        0x101a67ff7 +libboost_thread.dylib (0) <FD27C445-A73B-392A-B7C7-7A9C419BA0C8> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_thread.dylib
       0x101a6f000 -        0x101a71fff +libboost_chrono-mt.dylib (0) <8FA281FE-6D12-3E2C-A7DE-F851F9C23F53> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x101a74000 -        0x101b77ff3 +QtNetwork (0) <DD8EF1B7-0C03-386D-AE11-E618BC4C87F3> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x101bbd000 -        0x101fe9ff7 +QtWidgets (0) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10214a000 -        0x102577ff7 +QtGui (0) <96CF196B-1BBB-317F-9F39-86DD41787FC9> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x102671000 -        0x102b52fff +QtCore (0) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x102c06000 -        0x102c60ff7 +QtDBus (0) <6BFE4F79-D9C9-381E-A68D-BB5E6FFEDF4E> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x102c78000 -        0x102daaff7 +libprotobuf.15.dylib (0) <7126DB9C-1EE3-36D1-B366-9047D43A8A3C> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x102e5a000 -        0x102f72feb +libdb_cxx-4.8.dylib (0) <A513D80B-6037-3066-B163-C800B68C9019> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x102f98000 -        0x102fa8ff3 +libz.1.dylib (0) <ACB7269B-A127-30F2-8EE4-1F6E0B286AF1> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libz.1.dylib
       0x102fac000 -        0x102fd8ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x102fe5000 -        0x102fedff7 +libminiupnpc.16.dylib (0) <062F4A0E-32DB-36B6-B504-8734C0E61FB2> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x102ff1000 -        0x10303bff7 +libssl.1.0.0.dylib (0) <FFB2C5A8-1496-3CCD-A72B-B99C228CF433> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x103057000 -        0x1031dc91f +libcrypto.1.0.0.dylib (0) <09C0330E-76BF-302A-9549-AC02D38B87D0> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x105be1000 -        0x105c2b9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff314e3000 -     0x7fff32341fff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff32393000 -     0x7fff32393fff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff33f04000 -     0x7fff343a5fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff35070000 -     0x7fff35070fff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff36058000 -     0x7fff3641efff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff59a88000 -     0x7fff59abbff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff59fc2000 -     0x7fff59fc3ffb  libSystem.B.dylib (1252.50.4) <C7810EA7-A61F-3817-8E54-E2EC4E26F946> /usr/lib/libSystem.B.dylib
    0x7fff5a1f7000 -     0x7fff5a24dfff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff5a24e000 -     0x7fff5a272ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5b671000 -     0x7fff5ba5f7e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff5c135000 -     0x7fff5c139ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff5c13a000 -     0x7fff5c144ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5c145000 -     0x7fff5c14cfff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5c14d000 -     0x7fff5c156ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5c157000 -     0x7fff5c1dcfff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5c264000 -     0x7fff5c29dff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff5c29e000 -     0x7fff5c2bbff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff5c2bc000 -     0x7fff5c2bcffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff5c2ca000 -     0x7fff5c2caff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff5c2cb000 -     0x7fff5c2cfffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff5c2d0000 -     0x7fff5c2d2ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff5c2d3000 -     0x7fff5c2d4ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff5c2d5000 -     0x7fff5c2ecfff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff5c2ed000 -     0x7fff5c2edfff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5c2ee000 -     0x7fff5c377ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff5c378000 -     0x7fff5c37bffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5c37c000 -     0x7fff5c37fffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5c380000 -     0x7fff5c381fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5c382000 -     0x7fff5c388ff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5c389000 -     0x7fff5c3d2ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff5c3d3000 -     0x7fff5c3f9ff7  libsystem_kernel.dylib (4570.51.1) <5CAAB092-02CC-3A37-9D5F-C4AD1083AB96> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5c3fa000 -     0x7fff5c445fcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff5c446000 -     0x7fff5c465fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5c466000 -     0x7fff5c596ff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff5c597000 -     0x7fff5c5a1ffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5c5a2000 -     0x7fff5c5abff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff5c5ac000 -     0x7fff5c5b3ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff5c5b4000 -     0x7fff5c5bffff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5c5c0000 -     0x7fff5c5c3fff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5c5c4000 -     0x7fff5c5c5ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5c5c6000 -     0x7fff5c5cdff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5c5ce000 -     0x7fff5c5e1fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff5c5e3000 -     0x7fff5c5e8ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff5c5e9000 -     0x7fff5c616fff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

Model: MacBookAir7,2, BootROM MBA71.0176.B00, 2 processors, Intel Core i5, 1.6 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Bluetooth: Version 6.0.5f3, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by brakmic** [comment]
You're using some older version. 

Please, download the DMG for the latest version from our [release pages](https://github.com/deeponion/deeponion/releases/latest). 
Also, take into account that you **must have** certain **libraries pre-installed**. Check our [Mac docs here](https://github.com/deeponion/deeponion/blob/master/doc/build_macos.md).

**Comment by nilathj** [comment]
I am using the latest DeepOnion-Qt-DV-163-Mac.dmg.  The instructions that you linked are to build the package. So you mean to say the latest package doesn't have all the dependencies in it?

**Comment by nilathj** [comment]
Process:               DeepOnion-Qt [15070]
Path:                  /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
Identifier:            org.deeponion.DeepOnion-Qt
Version:               1.6.2 (1.6.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DeepOnion-Qt [15070]
User ID:               501

Date/Time:             2018-04-20 21:34:06.491 +1000
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        E13302FA-A969-660A-B213-0FE106AFF0F3

Sleep/Wake UUID:       4AEFE549-3B2E-464D-B449-E60D74C5BD28

Time Awake Since Boot: 97000 seconds
Time Since Wake:       280 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
  Reason: image not found

Binary Images:
       0x103834000 -        0x103f56fff +org.deeponion.DeepOnion-Qt (1.6.2 - 1.6.2) <ACC84206-56D4-3CFC-8D57-8B027F1361A7> /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
       0x104063000 -        0x104065ff7 +libboost_system.dylib (0) <5CFD618D-2AF4-3C59-88C2-B0CE6CCA7265> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10406f000 -        0x10407dfff +libboost_filesystem.dylib (0) <E0F26994-D113-3440-9645-6E4FB91ABF19> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10408c000 -        0x1040bcfff +libboost_program_options-mt.dylib (0) <4280CB1D-C6B9-350D-B89E-5BBFFEBE8896> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x1040dc000 -        0x1040e8ff7 +libboost_thread.dylib (0) <FD27C445-A73B-392A-B7C7-7A9C419BA0C8> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_thread.dylib
       0x1040f6000 -        0x1040f8fff +libboost_chrono-mt.dylib (0) <8FA281FE-6D12-3E2C-A7DE-F851F9C23F53> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1040fb000 -        0x1041feff3 +QtNetwork (0) <DD8EF1B7-0C03-386D-AE11-E618BC4C87F3> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x104249000 -        0x104675ff7 +QtWidgets (0) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1047d9000 -        0x104c06ff7 +QtGui (0) <96CF196B-1BBB-317F-9F39-86DD41787FC9> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x104d00000 -        0x104d5aff7 +QtDBus (0) <6BFE4F79-D9C9-381E-A68D-BB5E6FFEDF4E> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x104d72000 -        0x104ea4ff7 +libprotobuf.15.dylib (0) <7126DB9C-1EE3-36D1-B366-9047D43A8A3C> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x104f54000 -        0x104f64ff3 +libz.1.dylib (0) <ACB7269B-A127-30F2-8EE4-1F6E0B286AF1> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libz.1.dylib
       0x104f68000 -        0x104f94ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x104fa1000 -        0x104fa9ff7 +libminiupnpc.16.dylib (0) <062F4A0E-32DB-36B6-B504-8734C0E61FB2> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x104fd1000 -        0x10501b9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
       0x10506f000 -        0x105550fff +QtCore (0) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x105604000 -        0x10571cfeb +libdb_cxx-4.8.dylib (0) <A513D80B-6037-3066-B163-C800B68C9019> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x105742000 -        0x10578cff7 +libssl.1.0.0.dylib (0) <FFB2C5A8-1496-3CCD-A72B-B99C228CF433> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x1057a8000 -        0x10592d91f +libcrypto.1.0.0.dylib (0) <09C0330E-76BF-302A-9549-AC02D38B87D0> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
    0x7fff314e3000 -     0x7fff32341fff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff32393000 -     0x7fff32393fff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff33f04000 -     0x7fff343a5fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff35070000 -     0x7fff35070fff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff36058000 -     0x7fff3641efff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff59a88000 -     0x7fff59abbff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff59fc2000 -     0x7fff59fc3ffb  libSystem.B.dylib (1252.50.4) <C7810EA7-A61F-3817-8E54-E2EC4E26F946> /usr/lib/libSystem.B.dylib
    0x7fff5a1f7000 -     0x7fff5a24dfff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff5a24e000 -     0x7fff5a272ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5b671000 -     0x7fff5ba5f7e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff5c135000 -     0x7fff5c139ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff5c13a000 -     0x7fff5c144ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5c145000 -     0x7fff5c14cfff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5c14d000 -     0x7fff5c156ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff5c157000 -     0x7fff5c1dcfff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5c264000 -     0x7fff5c29dff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff5c29e000 -     0x7fff5c2bbff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff5c2bc000 -     0x7fff5c2bcffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff5c2ca000 -     0x7fff5c2caff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff5c2cb000 -     0x7fff5c2cfffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff5c2d0000 -     0x7fff5c2d2ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff5c2d3000 -     0x7fff5c2d4ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff5c2d5000 -     0x7fff5c2ecfff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff5c2ed000 -     0x7fff5c2edfff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5c2ee000 -     0x7fff5c377ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff5c378000 -     0x7fff5c37bffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5c37c000 -     0x7fff5c37fffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5c380000 -     0x7fff5c381fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5c382000 -     0x7fff5c388ff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5c389000 -     0x7fff5c3d2ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff5c3d3000 -     0x7fff5c3f9ff7  libsystem_kernel.dylib (4570.51.1) <5CAAB092-02CC-3A37-9D5F-C4AD1083AB96> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5c3fa000 -     0x7fff5c445fcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff5c446000 -     0x7fff5c465fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5c466000 -     0x7fff5c596ff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff5c597000 -     0x7fff5c5a1ffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5c5a2000 -     0x7fff5c5abff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff5c5ac000 -     0x7fff5c5b3ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff5c5b4000 -     0x7fff5c5bffff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5c5c0000 -     0x7fff5c5c3fff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5c5c4000 -     0x7fff5c5c5ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5c5c6000 -     0x7fff5c5cdff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5c5ce000 -     0x7fff5c5e1fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff5c5e3000 -     0x7fff5c5e8ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff5c5e9000 -     0x7fff5c616fff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

Model: MacBookAir7,2, BootROM MBA71.0176.B00, 2 processors, Intel Core i5, 1.6 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Bluetooth: Version 6.0.5f3, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by brakmic** [comment]
Please, follow our tutorial. 
Also check our forums, as we have explained this many, many times. 
There are some issues with dynamic/static linking on Mac and those tutorials are there to help our users.

**Comment by nilathj** [comment]
Cheers will do.
