### ISSUE TITLE
Error when attempting make command on macOS 10.13.4

### ISSUE THREAD

**Issue by chisNaN** [deeponion/deeponion-legacy#99]
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
  OBJCXXLD qt/DeepOnion-qt
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in DeepOnion_qt-bitcoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/DeepOnion-qt] Error 1
make: *** [all-recursive] Error 1

**Comment by deeponion** [comment]
please check https://github.com/deeponion/deeponion/issues/75
same issue, and the solution is there.

**Comment by chisNaN** [comment]
Thanks again for you reactivity. Really valuable

**Comment by chisNaN** [comment]
Sorry to bother again.
I tried the mentioned trick to change content file of `src/qt/bitcoin.qrc` and `src/qt/bitcoin_locale.qrc`
and i checked there is no `src/qt/locale/bitcoin_sc.qm`
before running the make command again
but still i have this slightly different error message (about x86_64 archi) at make command

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-moc_bitcoinunits.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: qt/libbitcoinqt.a(libbitcoinqt_a-qrc_bitcoin.o) has no symbols
  OBJCXXLD qt/DeepOnion-qt
Undefined symbols for architecture x86_64:
  "qInitResources_bitcoin()", referenced from:
      _main in DeepOnion_qt-bitcoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/DeepOnion-qt] Error 1
make: *** [all-recursive] Error 1
```
